on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

name: kasm

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
